// frameworks/vue/src/components/pages/Calendar/Calendar.vue
<script setup lang="ts">
import CalendarBody from "./components/features/CalendarBody/CalendarBody.vue"
import { useHooks } from "./useHooks"

const {
  currentMonth,
  currentYear,
  handleNextMonthClick,
  handlePreviousMonthClick,
  taskList,
} = useHooks()
</script>

<template>
  <div>
    <CalendarBody
      :current-month="currentMonth"
      :current-year="currentYear"
      :handle-next-month-click="handleNextMonthClick"
      :handle-previous-month-click="handlePreviousMonthClick"
      :task-list="taskList"
    />
  </div>
</template>

// frameworks/react/src/components/pages/Calendar/index.tsx
"use client"

import { CalendarBody } from "./components/features/CalendarBody"
import { useHooks } from "./useHooks"

import type { FC } from "react"

export const Calendar: FC = () => {
  const props = useHooks()

  return (
    <div>
      <CalendarBody {...props} currentMonth={7} currentYear={2026} />
    </div>
  )
}
