// frameworks/react/src/components/pages/Calendar/components/features/CalendarBody/index.tsx
import { CalendarCell } from "./components/features/CalendarCell"
import { TaskList } from "./components/features/TaskList"
import { MonthSelector } from "./components/layouts/MonthSelector"
import { DayCell } from "./components/ui/DayCell"
import { SiblingMonthButton } from "./components/ui/SiblingMonthButton"
import { getDates } from "./modules/getDates"
import { getTargetTaskList } from "./modules/getTargetTaskList"

import styles from "./index.module.css"

import type { Task } from "@/domains/Task"
import type { FC } from "react"

type Props = {
  currentMonth: number
  currentYear: number
  handleNextMonthClick: () => void
  handlePreviousMonthClick: () => void
  taskList: readonly Task[]
}

const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]

export const CalendarBody: FC<Props> = (props) => {
  const {
    currentMonth,
    currentYear,
    handleNextMonthClick,
    handlePreviousMonthClick,
    taskList,
  } = props
  const dates = getDates(currentYear, currentMonth)

  return (
    <div className={styles.root}>
      <MonthSelector
        monthElement={<div>{currentMonth}月</div>}
        previousButtonElement={
          <SiblingMonthButton
            direction="previous"
            handleClick={handlePreviousMonthClick}
          />
        }
        nextButtonElement={
          <SiblingMonthButton
            direction="next"
            handleClick={handleNextMonthClick}
          />
        }
      />

      <ul className={styles.ul}>
        {DAYS.map((day) => (
          <li key={day}>
            <DayCell day={day} />
          </li>
        ))}

        {dates.map((date) => {
          const isCurrentMonth = date.getMonth() + 1 === currentMonth
          const targetTaskList = taskList.reduce(getTargetTaskList(date), [])

          return (
            <li key={date.toISOString()}>
              <CalendarCell
                date={date}
                isCurrentMonth={isCurrentMonth}
                taskListElement={<TaskList taskList={targetTaskList} />}
              />
            </li>
          )
        })}
      </ul>
    </div>
  )
}

// frameworks/angular/src/components/pages/calendar/components/features/calendar-body/calendar-body.ts
import { Component, computed, input, output } from "@angular/core";
import { DayCell } from "./components/ui/day-cell/day-cell";
import { getDates } from "./modules/getDates";
import { getTargetTaskList } from "./modules/getTargetTaskList";
import { CalendarCell } from "./components/features/calendar-cell/calendar-cell";
import { TaskList } from "./components/features/task-list/task-list";
import { MonthSelector } from "./components/layouts/month-selector/month-selector";
import { SiblingMonthButton } from "./components/ui/sibling-month-button/sibling-month-button";

import type { Task } from "../../../../../../domains/Task";

@Component({
  selector: "calendar-body",
  templateUrl: "./calendar-body.html",
  styleUrls: ["./calendar-body.css"],
  imports: [DayCell, CalendarCell, MonthSelector, SiblingMonthButton, TaskList],
})
export class CalendarBody {
  public readonly currentMonth = input.required<number>();
  public readonly currentYear = input.required<number>();
  public readonly taskList = input.required<readonly Task[]>();
  public readonly handleNextMonthClick = output();
  public readonly handlePreviousMonthClick = output();
  protected readonly DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] as const;
  protected readonly dates = computed(() => getDates(this.currentYear(), this.currentMonth()));

  protected readonly getCellTaskList = (date: Date) =>
    this.taskList().reduce(getTargetTaskList(date), [] as Pick<Task, "id" | "title">[]);
}
