// frameworks/vue/src/components/ui/Header/Header.vue
<script setup lang="ts">
const NAVIGATION_DATA = [
  { label: "Top", href: "/" },
  { label: "Calendar", href: "/calendar" },
  { label: "Create schedule", href: "/task/create" },
] as const
</script>

<template>
  <header :class="$style.header">
    <nav>
      <ul :class="$style.ul">
        <li v-for="navigation in NAVIGATION_DATA" :key="navigation.href">
          <RouterLink :to="navigation.href">{{ navigation.label }}</RouterLink>
        </li>
      </ul>
    </nav>
  </header>
</template>

<style module>
.header {
  border-bottom: 1px solid var(--foreground);
  padding: 12px;
}

.ul {
  display: flex;
  column-gap: 8px;
}
</style>

// frameworks/react/src/components/ui/Header/index.tsx
import Link from "next/link"
import styles from "./index.module.css"

import type { FC } from "react"

const NAVIGATION_DATA = [
  {
    label: "Top",
    href: "/",
  },
  {
    label: "Calendar",
    href: "/calendar",
  },
  {
    label: "Create schedule",
    href: "/task/create",
  },
] as const

export const Header: FC = () => {
  return (
    <header className={styles.header}>
      <nav>
        <ul className={styles.ul}>
          {NAVIGATION_DATA.map((navigation) => {
            const { href, label } = navigation

            return (
              <li key={href}>
                <Link href={href}>{label}</Link>
              </li>
            )
          })}
        </ul>
      </nav>
    </header>
  )
}
