// frameworks/react/src/components/pages/Calendar/components/features/CalendarBody/components/features/TaskList/index.tsx
import Link from "next/link"

import styles from "./index.module.css"

import type { FC } from "react"
import type { Task } from "@/domains/Task"

type Props = {
  taskList: readonly Pick<Task, "id" | "title">[]
}

export const TaskList: FC<Props> = (props) => {
  const { taskList } = props

  if (taskList.length === 0) return null

  return (
    <ul className={styles.root}>
      {taskList.map((taskData) => {
        const { id, title } = taskData

        return (
          <li key={id} className={styles.li}>
            <Link href={`/task/${id}`} className={styles.listAnchor}>
              {title}
            </Link>
          </li>
        )
      })}
    </ul>
  )
}

// frameworks/vue/src/components/pages/Calendar/components/features/CalendarBody/components/features/TaskList/TaskList.vue
<script setup lang="ts">
import type { Task } from "@/domains/Task"

defineProps<{ taskList: readonly Pick<Task, "id" | "title">[] }>()
</script>

<template>
  <ul v-if="taskList.length > 0" :class="$style.root">
    <li v-for="taskData in taskList" :key="taskData.id" :class="$style.li">
      <RouterLink :to="`/task/${taskData.id}`" :class="$style.listAnchor">{{
        taskData.title
      }}</RouterLink>
    </li>
  </ul>
</template>

<style module>
.root {
  display: flex;
  row-gap: 4px;
  z-index: 20;
  flex-direction: column;
}

.li {
  overflow: hidden;
}

.listAnchor {
  display: block;
  width: 100%;
  overflow: hidden;
  text-align: left;
  text-overflow: ellipsis;
  white-space: nowrap;
  text-decoration: none;
}

.listAnchor:hover {
  text-decoration: underline;
}
</style>
