// frameworks/vue/src/components/pages/Calendar/components/features/CalendarBody/components/features/CalendarCell/CalendarCell.vue
<script setup lang="ts">
import { computed } from "vue"

import { formatScheduleDate } from "@/utilities/formatScheduleDate"

const props = defineProps<{
  date: Date
  isCurrentMonth: boolean
}>()

const cellOpacity = computed(() => (props.isCurrentMonth ? 1 : 0.6))
const currentDate = computed(() => props.date.getDate())
const createHref = computed(
  () => `/task/create?date=${formatScheduleDate(props.date)}`,
)
</script>

<template>
  <div :class="$style.root" :style="{ '--opacity': cellOpacity }">
    <header :class="$style.header">{{ currentDate }}</header>

    <slot name="taskList" />

    <RouterLink :to="createHref" :class="$style.cellLink" />
  </div>
</template>

<style module>
.root {
  background-color: var(--secondary-background);
  position: relative;
  padding: 8px;
  display: flex;
  flex-direction: column;
  row-gap: 8px;
  opacity: var(--opacity);
  height: 100%;
  justify-content: flex-start;
}

.header {
  position: relative;
  z-index: 20;
  pointer-events: none;
}

.cellLink {
  position: absolute;
  inset: 0;
  z-index: 10;
}
</style>

// frameworks/react/src/components/pages/Calendar/components/features/CalendarBody/components/features/CalendarCell/index.tsx
import Link from "next/link"

import { formatScheduleDate } from "@/utilities/formatScheduleDate"

import styles from "./index.module.css"

import type { CSSProperties, FC, ReactElement } from "react"

type Props = {
  date: Date
  isCurrentMonth: boolean
  taskListElement: ReactElement
}

const getCellColor = (isCurrentMonth: boolean) => {
  return isCurrentMonth ? 1 : 0.6
}

export const CalendarCell: FC<Props> = (props) => {
  const { date, isCurrentMonth, taskListElement } = props
  const cellColor = {
    "--opacity": getCellColor(isCurrentMonth),
  } as CSSProperties
  const currentDate = date.getDate()

  return (
    <div className={styles.root} style={cellColor}>
      <header className={styles.header}>{currentDate}</header>

      {taskListElement}

      <Link
        href={`/task/create?date=${formatScheduleDate(date)}`}
        className={styles.cellLink}
      />
    </div>
  )
}
