// frameworks/angular/src/components/pages/calendar/components/features/calendar-body/components/features/calendar-cell/calendar-cell.ts
import { Component, computed, input } from "@angular/core";
import { RouterLink } from "@angular/router";

import { formatScheduleDate } from "../../../../../../../../../utilities/formatScheduleDate";

const getCellColor = (isCurrentMonth: boolean) => {
  return isCurrentMonth ? 1 : 0.6;
};

@Component({
  selector: "calendar-cell",
  templateUrl: "./calendar-cell.html",
  styleUrls: ["./calendar-cell.css"],
  imports: [RouterLink],
})
export class CalendarCell {
  public readonly date = input.required<Date>();
  public readonly isCurrentMonth = input.required<boolean>();

  protected readonly cellColor = computed(() => ({
    "--opacity": getCellColor(this.isCurrentMonth()),
  }));
  protected readonly currentDate = computed(() => this.date().getDate());
  protected readonly queryParameters = computed(() => ({
    date: formatScheduleDate(this.date()),
  }));
}

// frameworks/react/src/components/pages/Calendar/components/features/CalendarBody/components/features/CalendarCell/index.tsx
import Link from "next/link"

import { formatScheduleDate } from "@/utilities/formatScheduleDate"

import styles from "./index.module.css"

import type { CSSProperties, FC, ReactElement } from "react"

type Props = {
  date: Date
  isCurrentMonth: boolean
  taskListElement: ReactElement
}

const getCellColor = (isCurrentMonth: boolean) => {
  return isCurrentMonth ? 1 : 0.6
}

export const CalendarCell: FC<Props> = (props) => {
  const { date, isCurrentMonth, taskListElement } = props
  const cellColor = {
    "--opacity": getCellColor(isCurrentMonth),
  } as CSSProperties
  const currentDate = date.getDate()

  return (
    <div className={styles.root} style={cellColor}>
      <header className={styles.header}>{currentDate}</header>

      {taskListElement}

      <Link
        href={`/task/create?date=${formatScheduleDate(date)}`}
        className={styles.cellLink}
      />
    </div>
  )
}
