// frameworks/react/src/components/pages/TaskId/index.tsx
"use client"

import Link from "next/link"

import { TaskDetail } from "@/components/layouts/TaskDetail"

import { useHooks } from "./useHooks"

import styles from "./index.module.css"

import type { FC } from "react"

type Props = {
  id: string
}

export const TaskId: FC<Props> = (props) => {
  const { task } = useHooks(props)

  if (task === null) return null

  const { body, date, id, title } = task

  return (
    <div>
      <TaskDetail
        bodyNode={body}
        dateNode={date}
        idNode={id}
        titleNode={title}
      />

      <div className={styles.editWrapper}>
        <Link href={`/task/${id}/edit`}>edit</Link>
      </div>
    </div>
  )
}

// frameworks/vue/src/components/pages/TaskId/TaskId.vue
<script setup lang="ts">
import TaskDetail from "@/components/layouts/TaskDetail/TaskDetail.vue"

import { useHooks } from "./useHooks"

const props = defineProps<{ id: string }>()

const { task } = useHooks(props)
</script>

<template>
  <div v-if="task !== null">
    <TaskDetail :id="task.id">
      <template #title>{{ task.title }}</template>
      <template #date>{{ task.date }}</template>
      <template #body>{{ task.body }}</template>
    </TaskDetail>

    <div :class="$style.editWrapper">
      <RouterLink :to="`/task/${task.id}/edit`">edit</RouterLink>
    </div>
  </div>
</template>

<style module>
.editWrapper {
  margin-top: 16px;
}
</style>
