// frameworks/react/src/components/pages/Calendar/components/features/CalendarBody/components/ui/SiblingMonthButton/index.tsx
import type { FC } from "react"

type Props = {
  direction: "previous" | "next"
  handleClick: () => void
}

export const SiblingMonthButton: FC<Props> = (props) => {
  const { direction, handleClick } = props

  return (
    <button onClick={handleClick}>
      {direction === "previous" ? "◀" : "▶"}
    </button>
  )
}

// frameworks/angular/src/components/pages/calendar/components/features/calendar-body/components/ui/sibling-month-button/sibling-month-button.ts
import { Component, computed, input, output } from "@angular/core";

const getDirectionIcon = (direction: "previous" | "next") => {
  return direction === "previous" ? "◀" : "▶";
};

@Component({
  selector: "sibling-month-button",
  templateUrl: "./sibling-month-button.html",
})
export class SiblingMonthButton {
  public readonly direction = input.required<"previous" | "next">();
  public readonly handleClick = output();

  protected readonly icon = computed(() => getDirectionIcon(this.direction()));
}
